### ISSUE TITLE
Get network error when tried to connect wallet

### ISSUE THREAD

**Issue by mistricky** [Crossbell-Box/xLog-mobile#198]
![1911689091682_ pic](https://github.com/Crossbell-Box/xLog-mobile/assets/22574136/9db66720-cf37-419b-8476-b5f8a4071c05)

### Issue description
I have tried to press the `Connect Wallet` button, but nothing happened. And after a few seconds, a toast message showed up saying 'Network error'.

I checked my network status, but everything seems to be working fine, even though I tried to close/open the system network proxy, it's expected? or did I miss anything here?

**Comment by dohooo** [comment]
I also encountered this problem, but when I turned on the VPN globally, it was resolved.
