### ISSUE TITLE
Bug: Fail to load personal posts 

### ISSUE THREAD

**Issue by LumenYoung** [Crossbell-Box/xLog-mobile#252]
As shown in the picture, the app is unable to display the post from my personal blog. But every other one's works fine, so I don't think it is a network issue.

Since I didn't do anything other than download the app and log in to my account, there is no clear reproduce step. 

I'm delighted to provide any additional information upon request.

![Screenshot_20231027-191810.png](https://github.com/Crossbell-Box/xLog-mobile/assets/45258158/455ac81f-cc27-4ed3-af0a-32e87773b4ad)

**Comment by dohooo** [comment]
Thanks for your reminder, I'll check it ASAP.

**Comment by dohooo** [comment]
This problem has been resolved in dev branch. We'll release it in few days. thx

**Comment by LumenYoung** [comment]
Thanks for the prompt reply and thanks for the work!
